/* common.h
 */
#include "funcs.h"
C
      FLOAT STKR(N_SIZE),STKI(N_SIZE)
      CHARACTER IDSTK(4,48)
      INTEGER LSTK(48),MSTK(48),NSTK(48),VSIZE,LSIZE,BOT,TOP
      CHARACTER IDS(4,32)
      INTEGER PSTK(32),RSTK(32),PSIZE,PT,PTZ
      CHARACTER ALFA(52),ALFB(52)
      INTEGER ALFL,CASE
      CHARACTER LIN(MAX_LINE)
      INTEGER DDT,ERR,FMT,LCT(4),LPT(6),HIO,RIO,WIO,RTE,WTE
      CHARACTER BUF(BUF_SIZE)
      CHARACTER SYN(4)
      INTEGER SYM,CHAR,FLP(2),FIN,FUN,LHS,RHS,RAN(2)
C
      COMMON /VSTK/ STKR,STKI,IDSTK,LSTK,MSTK,NSTK,VSIZE,LSIZE,BOT,TOP
      COMMON /RECU/ IDS,PSTK,RSTK,PSIZE,PT,PTZ
      COMMON /ALFS/ ALFA,ALFB,ALFL,CASE
      COMMON /IOP/ DDT,ERR,FMT,LCT,LIN,LPT,HIO,RIO,WIO,RTE,WTE
      COMMON /COM/ SYM,SYN,BUF,CHAR,FLP,FIN,FUN,LHS,RHS,RAN
