#include "matlab.h"
      SUBROUTINE FILES(LUNIT,NAM)
      INTEGER LUNIT,NAM(32)
C
C     SYSTEM DEPENDENT ROUTINE TO ALLOCATE FILES
C     LUNIT = LOGICAL UNIT NUMBER
C     NAM = FILE NAME, 1 CHARACTER PER WORD
C
      CHARACTER NAMEC(32)
C
      WRITE(1,100) LUNIT
  100 FORMAT(1X,'FILES ',I6)
C
      IF (LUNIT .EQ. 0) RETURN
      IF (LUNIT .EQ. 1) RETURN
C
      IF (LUNIT .NE. 9) GO TO 1
      CALL OPEN(9, 'MATLAB  HLP', 0)
      READ(9,2,ERR=3)
    2 FORMAT(/)
      REWIND 9
      WRITE(1,6)
    6 FORMAT(/1X,'HELP IS AVAILABLE')
      RETURN
    3 WRITE(1,4)
    4 FORMAT(/1X,'MATLAB.HLP NOT AVAILABLE')
      CALL EXIT
    1 CONTINUE
C
      IF (LUNIT .NE. -9) GO TO 5
      REWIND 9
      RETURN
    5 CONTINUE
C
      IF (LUNIT .GE. 0) GO TO 7
      I = -LUNIT
      ENDFILE I
      RETURN
    7 CONTINUE
C
      DO 8 I=1,32
        NAMEC(I) = NAM(I)
    8 CONTINUE
      CALL OPEN(LUNIT, NAMEC, 0)
C
      RETURN
      END

